openapi: 3.0.1
info:
  title: Microservicio Cuentas y Movimientos
  version: 1.0.0
  description: API para gestión de cuentas y movimientos
servers:
  - url: http://localhost:8082
    description: Local server
paths:
  /cuentas:
    get:
      summary: Obtener todas las cuentas
      responses:
        '200':
          description: Lista de cuentas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cuenta'
    post:
      summary: Crear una nueva cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
      responses:
        '201':
          description: Cuenta creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
  /cuentas/{id}:
    get:
      summary: Obtener cuenta por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cuenta encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
        '404':
          description: Cuenta no encontrada
  /movimientos:
    get:
      summary: Obtener todos los movimientos
      responses:
        '200':
          description: Lista de movimientos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movimiento'
    post:
      summary: Crear un nuevo movimiento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movimiento'
      responses:
        '201':
          description: Movimiento creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movimiento'
  /reportes:
    get:
      summary: Generar reporte de movimientos
      parameters:
        - name: fecha
          in: query
          schema:
            type: string
        - name: cliente
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Reporte generado
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Cuenta:
      type: object
      properties:
        id:
          type: integer
        tipoCuenta:
          type: string
        saldoInicial:
          type: number
        estado:
          type: boolean
    Movimiento:
      type: object
      properties:
        id:
          type: integer
        fecha:
          type: string
          format: date
        tipoMovimiento:
          type: string
        valor:
          type: number
        saldo:
          type: number
